name: flutter_form_registry
description: A workaround to track some FormFields in the tree.
version: 0.3.5
homepage:

environment:
  sdk: ">=2.12.0 <2.14.0"
  flutter: ">=1.17.0 <2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
